### ISSUE TITLE
Question regarding explainjs vs docco

### ISSUE THREAD

**Issue by chenglou** [bendytree/explainjs#3]
Hi, I'm searching for a literate-style documentation generator and found this project.

I was wondering how explainjs differs from [Docco](https://github.com/jashkenas/docco), which is used to parse Backbone and underscore. From the demo of your page, the results look quite alike.

Thanks and keep up the good work!

**Comment by bendytree** [comment]
My goal with ExplainJS was to build a website (explainjs.com) where people could quickly generate a nice view of their source code. I tried to use Docco but discovered that Docco does a lot of file systemy things which got in the way of explainjs.com's dynamic nature.

Docco is built around the command line and file system IO. You run `$ docco *.js`, it reads from the file system, it makes a `/docs` directory, and loads it with html files and other resources. If that's what you need (and for many people it is) then Docco's a good option. Other options include [jsdoc](https://github.com/jsdoc3/jsdoc), [YUIDoc](http://yui.github.io/yuidoc/), [Doxygen](http://www.stack.nl/~dimitri/doxygen/), and [JavaDoc](http://www.oracle.com/technetwork/java/javase/documentation/index-jsp-135444.html).

I just wanted to pass code to a function and get the results. To me, the IO part doesn't belong in the converter. Code should be convertible regardless of where it's from or where it's going. If someone wanted to do file systemy things then that probably belongs in a separate module.

So ExplainJS is just a JavaScript function where you pass code and it returns the results.

```
var explainjs = require('explainjs');
var code = "// call x \n x();";

explainjs(code, function(results){
    ...
});
```

There are other differences too...

Docco handles CoffeeScript and Literate styles nicely, but doesn't do multiline comments (like `/* */`). ExplainJS is really just for c style languages, but aims to handle those really well. The goal is that nicely written code should look nice in ExplainJS.

Docco is written in literate CoffeeScript and ExplainJS is plain JavaScript.

ExplainJS also has a few dozen tests (written in mocha) to prevent regression. Nothing special. I'm not a super avid "you have to test everything" guy, but for this type of library it's just easier. Plus I'm otherwise scared of regex.

**Comment by chenglou** [comment]
Alright thanks.
